site_name: 'ğŸœ: `abbrev`: Expand abbreviations ğŸœ'

theme:
  name: material

  palette:
    primary:
      'lime'

  font:
    text:
      Roboto
    code:
      Roboto Mono

extra_css: [extra.css]

plugins:
    - mkdocstrings
