site_name: 'ğŸœ: `abbrev`: `abbrev`: Tiny full-featured abbreviation expander ğŸœ'

theme:
  name: material

  palette:
    primary:
      'lime'

  font:
    text:
      Roboto
    code:
      Roboto Mono

extra_css: [extra.css]

plugins:
    - mkdocstrings
